version: '3'
services:
  backend:
    build: "."
    ports:
      - "80:5000"
    volumes:
      - ".:/app"
    environment:
      ENV: "docker"
      FLASK_ENV: "development"
    networks:
      - webnet
  mysql:
    build: "./db"
    ports:
      - "3306:3306"
#    volumes:
#      - "./redis:/data"
    networks:
      - webnet
#    command: redis-server
networks:
  webnet:
